import { midiNoteName } from '../core/preview.js';
import type { MotifNote } from '../core/types.js';
import type { HotkeyAction } from './hotkey-map.js';

/** Maximum URL-encoded state size sent to jweb as one Max atom. */
const MAX_INLINE_LIBRARY_STATE_CHARACTERS = 6_000;
/** Encoded state characters carried by each bounded transport envelope. */
const LIBRARY_STATE_CHUNK_CHARACTERS = 3_000;

/** Complete, nullable note representation consumed by the Library HTML form. */
export interface LibraryNoteData {
  /** Relative pitch offset or scale degree. */
  pitch: number;
  /** Optional hybrid-mode chromatic adjustment. */
  accidental: number | null;
  /** Note start in motif PPQ ticks. */
  at: number;
  /** Note duration in motif PPQ ticks. */
  duration: number;
  /** Optional gate multiplier. */
  gate: number | null;
  /** Optional absolute MIDI velocity. */
  velocity: number | null;
  /** Optional additive velocity adjustment. */
  velocityOffset: number | null;
  /** Optional multiplicative velocity adjustment. */
  velocityScale: number | null;
  /** Whether the note extends into the following note. */
  legato: boolean;
  /** Whether matching adjacent pitches are tied. */
  tie: boolean;
}

/** Display-ready hot-key mapping consumed by the Library page. */
export interface LibraryHotkeyData {
  /** MIDI pitch used as the trigger. */
  pitch: number;
  /** Ableton-style note label generated by the device. */
  label: string;
  /** Action performed by the mapped pitch. */
  action: HotkeyAction;
}

/** One transport-safe fragment of an encoded Library state. */
export interface LibraryStateChunk {
  /** Envelope discriminator understood by the Library page. */
  kind: 'state-chunk';
  /** Monotonic state transfer identity. */
  transferId: number;
  /** Zero-based fragment index. */
  index: number;
  /** Total number of fragments in this transfer. */
  total: number;
  /** Fragment of the already URL-encoded state. */
  data: string;
}

/**
 * Convert a sparse stored note into the complete shape expected by form controls.
 * @param {MotifNote} note Stored motif note.
 * @returns {LibraryNoteData} Form-safe note with explicit nulls and booleans.
 */
export function toLibraryNoteData(note: MotifNote): LibraryNoteData {
  return {
    pitch: note.pitch,
    accidental: note.accidental ?? null,
    at: note.at,
    duration: note.duration,
    gate: note.gate ?? null,
    velocity: note.velocity ?? null,
    velocityOffset: note.velocityOffset ?? null,
    velocityScale: note.velocityScale ?? null,
    legato: note.legato ?? false,
    tie: note.tie ?? false,
  };
}

/**
 * Add the display label needed by the Library without duplicating MIDI note-name rules in HTML.
 * @param {{ pitch: number; action: HotkeyAction }} mapping Stored hot-key mapping.
 * @returns {LibraryHotkeyData} Mapping with its Ableton-style note label.
 */
export function toLibraryHotkeyData(
  mapping: { pitch: number; action: HotkeyAction },
): LibraryHotkeyData {
  return {
    ...mapping,
    label: midiNoteName(mapping.pitch),
  };
}

/**
 * Encode one authoritative Library state into Max-safe jweb messages.
 *
 * URL encoding expands punctuation enough that an otherwise small motif can
 * exceed Max's per-atom string capacity. Large states are therefore split as
 * encoded text, then wrapped in independently decodable transport envelopes.
 *
 * @param {unknown} state Complete Library state owned by the device.
 * @param {number} transferId Monotonic identity for a chunked transfer.
 * @returns {string[]} URL-encoded direct state or bounded chunk envelopes.
 */
export function encodeLibraryStateMessages(state: unknown, transferId: number): string[] {
  const encodedState = encodeURIComponent(JSON.stringify(state));
  if (encodedState.length <= MAX_INLINE_LIBRARY_STATE_CHARACTERS) return [encodedState];

  const total = Math.ceil(encodedState.length / LIBRARY_STATE_CHUNK_CHARACTERS);
  return Array.from({ length: total }, (_, index) => {
    const payload: LibraryStateChunk = {
      kind: 'state-chunk',
      transferId,
      index,
      total,
      data: encodedState.slice(
        index * LIBRARY_STATE_CHUNK_CHARACTERS,
        (index + 1) * LIBRARY_STATE_CHUNK_CHARACTERS,
      ),
    };
    return encodeURIComponent(JSON.stringify(payload));
  });
}
