import type { HotkeyAction } from "./hotkey-map.js";

/** Discriminator used by bounded Library state envelopes. */
export const LIBRARY_STATE_CHUNK_KIND = "state-chunk";
/** Maximum URL-encoded state size sent to jweb as one Max atom. */
export const MAX_INLINE_LIBRARY_STATE_CHARACTERS = 6_000;
/** Encoded state characters carried by each bounded transport envelope. */
export const LIBRARY_STATE_CHUNK_CHARACTERS = 3_000;
/** Defensive upper bound accepted by the browser state assembler. */
export const MAX_LIBRARY_STATE_CHUNKS = 10_000;

/** Complete, nullable note representation consumed by the Library form. */
export interface LibraryNoteData {
  /** Relative pitch offset or scale degree. */
  pitch: number;
  /** Optional hybrid-mode chromatic adjustment. */
  accidental: number | null;
  /** Note start in motif PPQ ticks. */
  at: number;
  /** Note duration in motif PPQ ticks. */
  duration: number;
  /** Optional gate multiplier. */
  gate: number | null;
  /** Optional absolute MIDI velocity. */
  velocity: number | null;
  /** Optional additive velocity adjustment. */
  velocityOffset: number | null;
  /** Optional multiplicative velocity adjustment. */
  velocityScale: number | null;
  /** Whether the note extends into the following note. */
  legato: boolean;
  /** Whether matching adjacent pitches are tied. */
  tie: boolean;
}

/** Display-ready hot-key mapping consumed by the Library page. */
export interface LibraryHotkeyData {
  /** MIDI pitch used as the trigger. */
  pitch: number;
  /** Ableton-style note label generated by the device. */
  label: string;
  /** Action performed by the mapped pitch. */
  action: HotkeyAction;
}

/** One motif row in the Library browser. */
export interface LibraryBrowserItemData {
  /** Stable motif id. */
  id: string;
  /** Human-readable motif name. */
  name: string;
  /** Whether a duplicate name requires displaying the stable id. */
  showId: boolean;
  /** Root-relative browser folder. */
  folder: string;
  /** Hot keys targeting this motif. */
  hotkeys: LibraryHotkeyData[];
}

/** Device-owned decisions controlling Library actions. */
export interface LibraryActionState {
  /** Whether the selected motif is the active edit target. */
  editing: boolean;
  /** Whether editing can begin. */
  canEdit: boolean;
  /** Whether the active edit can be persisted. */
  canSave: boolean;
  /** Whether a Live clip can be imported. */
  canImportClip: boolean;
  /** Whether the configured library can be rescanned. */
  canRefreshLibrary: boolean;
}

/** Device edit-session state rendered by the Library. */
export interface LibraryEditingState {
  /** Whether an edit session is active. */
  active: boolean;
  /** Whether the edit differs from its saved snapshot. */
  dirty: boolean;
  /** Whether cancel removes a newly created motif. */
  created: boolean;
  /** Motif restored when editing is cancelled. */
  sourceId: string | null;
  /** Motif currently being edited. */
  targetId: string | null;
}

/** Full selected-motif representation rendered by the Library. */
export interface LibrarySelectedMotifData {
  /** Motif schema version. */
  schemaVersion: number;
  /** Stable motif id. */
  id: string;
  /** Human-readable motif name. */
  name: string;
  /** Motif description. */
  description: string;
  /** Stored pitch interpretation. */
  pitchMode: string;
  /** Meter used when the motif was authored. */
  sourceMeter: {
    /** Beats per source bar. */
    numerator: number;
    /** Source beat-note denominator. */
    denominator: number;
  };
  /** Stored motif length in PPQ ticks. */
  length: number;
  /** Optional motif-wide gate multiplier. */
  defaultGate: number | null;
  /** Optional velocity remapping values normalized for form controls. */
  velocityCurve: {
    /** Optional input range minimum. */
    inputMin: number | null;
    /** Optional input range maximum. */
    inputMax: number | null;
    /** Optional output range minimum. */
    outputMin: number | null;
    /** Optional output range maximum. */
    outputMax: number | null;
    /** Optional curve exponent. */
    exponent: number | null;
  };
  /** Preformatted note, meter, bar, and pitch-mode summary. */
  stats: string;
  /** Whether this motif ships with the device. */
  isBuiltin: boolean;
  /** Whether this motif currently has a user-library file. */
  isPersisted: boolean;
  /** Root-relative user-library folder. */
  folder: string;
  /** Hot keys targeting this motif. */
  hotkeys: LibraryHotkeyData[];
  /** Total editable notes. */
  noteCount: number;
  /** Maximum editable notes allowed by the device. */
  noteLimit: number;
  /** Whether the device permits appending another note. */
  canAddNote: boolean;
  /** Whether the device permits removing a note. */
  canRemoveNote: boolean;
  /** Complete editable note list. */
  notes: LibraryNoteData[];
}

/** Structured warning delivered to the Library modal. */
export interface LibraryAlert {
  /** Monotonic alert identity. */
  id: number;
  /** Short modal title. */
  title: string;
  /** Actionable user-facing details. */
  message: string;
}

/** Progress from the incremental user-library scan. */
export interface LibraryScanProgress {
  /** Filesystem entries examined so far. */
  processedEntries: number;
  /** Valid motifs accepted so far. */
  loadedMotifs: number;
}

/** Complete authoritative state emitted by the device to the Library page. */
export interface LibraryServerState {
  /** Active browser search query. */
  query: string;
  /** Filtered and sorted browser rows. */
  items: LibraryBrowserItemData[];
  /** Selected row within the filtered items, or -1. */
  selectedIndex: number;
  /** Complete selected motif data. */
  selected: LibrarySelectedMotifData | null;
  /** Current device edit session. */
  editing: LibraryEditingState;
  /** Configured user-library root. */
  libraryPath: string;
  /** Whether the configured root was loaded successfully. */
  libraryLoaded: boolean;
  /** Whether an incremental scan is active. */
  libraryScanning: boolean;
  /** Device-owned action availability. */
  actions: LibraryActionState;
  /** Latest user-facing warning. */
  alert: LibraryAlert | null;
  /** Incremental scan counters. */
  scanProgress: LibraryScanProgress | null;
}

/** One transport-safe fragment of an encoded Library state. */
export interface LibraryStateChunk {
  /** Envelope discriminator understood by the Library page. */
  kind: typeof LIBRARY_STATE_CHUNK_KIND;
  /** Monotonic state transfer identity. */
  transferId: number;
  /** Zero-based fragment index. */
  index: number;
  /** Total number of fragments in this transfer. */
  total: number;
  /** Fragment of the already URL-encoded state. */
  data: string;
}
