/**
 * Build Motif runtime artifacts and generate a patch that references
 * content-addressed JavaScript filenames.
 *
 * The hand-written Max bridge (`MAX_BRIDGE`) is concatenated **before** the
 * esbuild IIFE so Max can discover a top-level `anything()` at global scope.
 * Handlers created inside the IIFE or via esbuild `footer` are not visible to
 * Max message dispatch.
 *
 * @see https://docs.cycling74.com/apiref/js/jsthis/#anything
 * @see https://docs.cycling74.com/apiref/js/jsthis/#messagename
 * @see https://docs.cycling74.com/apiref/js/jsthis/#arrayfromargs
 * @see https://docs.cycling74.com/apiref/js/error/
 */

import { createHash } from 'node:crypto';
import { build, transform } from 'esbuild';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { generateMaxPatch } from './generate-max-patch.js';
import path from 'node:path';

import type { Motif } from '../src/core/types.js';

/**
 * Read sorted builtin JSON files and emit the TypeScript module.
 * @returns {Promise<void>} A promise that resolves after the module is written.
 */
export async function generateBuiltins(): Promise<void> {
  const directory = path.resolve('motifs/builtin');
  const files = (await readdir(directory)).filter((file) => file.endsWith('.json')).sort();
  const motifs: Motif[] = [];
  for (const file of files) {
    motifs.push(JSON.parse(await readFile(path.join(directory, file), 'utf8')) as Motif);
  }

  const output = `// Generated by scripts/build.ts.
import type { Motif } from '../core/types.js';

export const BUILTIN_MOTIFS = ${JSON.stringify(motifs, null, 2)} as const satisfies readonly Motif[];
`;
  await mkdir('src/generated', { recursive: true });
  await writeFile('src/generated/builtins.ts', output);
}

/**
 * Top-level Max `v8` entry: route every unknown selector through MotifEngine.dispatch.
 * Uses Max globals `messagename` and `arrayfromargs` - not `this.messagename`.
 * @see https://docs.cycling74.com/apiref/js/jsthis/#anything
 * @see https://docs.cycling74.com/apiref/js/jsthis/#messagename
 * @see https://docs.cycling74.com/apiref/js/jsthis/#arrayfromargs
 */
const MAX_BRIDGE = 'var inlets=1;var outlets=1;function anything(){var message=messagename,args=arrayfromargs(arguments);if(typeof MotifEngine==="undefined"||typeof MotifEngine.dispatch!=="function"){error("Motif: engine dispatcher is unavailable for "+message+"\\n");return}return MotifEngine.dispatch(message,args)}';

const HASH_LENGTH = 12;

/**
 * Build a content-addressed JavaScript filename.
 * @param {string} stem The filename stem without its extension.
 * @param {string} content The exact file content Max will load.
 * @returns {string} A filename containing the leading SHA-256 digest.
 */
function hashedJavaScriptFilename(stem: string, content: string): string {
  const digest = createHash('sha256').update(content).digest('hex').slice(0, HASH_LENGTH);
  return `${stem}-${digest}.js`;
}

/**
 * Remove obsolete generated hashes while preserving the current artifact.
 * @param {string} directory The generated-artifact directory.
 * @param {string} stem The content-addressed filename stem.
 * @param {string} currentFilename The current artifact to retain.
 * @returns {Promise<void>} A promise that resolves after stale artifacts are removed.
 */
async function removeStaleHashedArtifacts(
  directory: string,
  stem: string,
  currentFilename: string,
): Promise<void> {
  const pattern = new RegExp(`^${stem}-[a-f0-9]{${HASH_LENGTH}}\\.js$`);
  const files = await readdir(directory);
  await Promise.all(
    files
      .filter((filename) => pattern.test(filename) && filename !== currentFilename)
      .map((filename) => rm(path.join(directory, filename), { force: true })),
  );
}

/**
 * List implementation TypeScript modules recursively, excluding declaration files.
 * @param {string} directory The source directory to inspect.
 * @returns {Promise<string[]>} Relative implementation-module paths.
 */
async function listTypeScriptModules(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async (entry) => {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return listTypeScriptModules(entryPath);
    return entry.isFile() && entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts')
      ? [entryPath]
      : [];
  }));
  return nested.flat().sort();
}

await generateBuiltins();

const [libraryHtml, previewSource] = await Promise.all([
  readFile('src/max/library.html', 'utf8'),
  readFile('src/max/motif-preview.js', 'utf8'),
]);
const libraryDigest = createHash('sha256').update(libraryHtml).digest('hex').slice(0, 12);
const libraryPageName = `uttori-motif-library-${libraryDigest}.html`;
const [buildResult, previewResult] = await Promise.all([
  build({
    entryPoints: ['src/max/device.ts'],
    bundle: true,
    format: 'iife',
    globalName: 'MotifEngine',
    platform: 'neutral',
    target: 'es2020',
    write: false,
    metafile: true,
    minify: true,
    sourcemap: false,
    legalComments: 'none',
    define: {
      __MOTIF_LIBRARY_HTML__: JSON.stringify(libraryHtml),
      __MOTIF_LIBRARY_PAGE_NAME__: JSON.stringify(libraryPageName),
    },
  }),
  transform(previewSource, {
    loader: 'js',
    // `jsui` runs in Max's legacy JavaScript host, not the `v8` object used by
    // the TypeScript engine. ES2020 minification can introduce template
    // literals and other syntax that the legacy host cannot safely parse.
    target: 'es5',
    minify: true,
    // Max 9.1.5's jsui error reporter can overflow while reporting a parser
    // error from one very long generated line. Keep production output minified
    // while bounding each line so a future incompatibility fails safely.
    lineLimit: 1_000,
    sourcemap: false,
    legalComments: 'none',
  }),
]);

const productionInputs = new Set(
  Object.keys(buildResult.metafile.inputs).map((input) => path.normalize(input)),
);
const unusedSourceModules = (await listTypeScriptModules('src'))
  .filter((modulePath) => !productionInputs.has(path.normalize(modulePath)));
if (unusedSourceModules.length > 0) {
  throw new Error(
    `Implementation modules under src must be reachable from the Max runtime; move test/script-only files out of src: ${unusedSourceModules.join(', ')}`,
  );
}

const engine = buildResult.outputFiles?.[0]?.text;
if (engine === undefined) throw new Error('esbuild did not produce the Max engine bundle');
const preview = previewResult.code;

const output = `${MAX_BRIDGE}\n${engine}`;
const engineFilename = hashedJavaScriptFilename('motif-device', output);
const previewFilename = hashedJavaScriptFilename('motif-preview', preview);

await rm('dist', { recursive: true, force: true });
await Promise.all([
  mkdir('dist', { recursive: true }),
  mkdir('max', { recursive: true }),
]);

await Promise.all([
  removeStaleHashedArtifacts('max', 'motif-device', engineFilename),
  removeStaleHashedArtifacts('max', 'motif-preview', previewFilename),
  // Stable-name Max copies were used by earlier builds but are not patch
  // dependencies. Remove them so a production folder contains only the exact
  // content-addressed artifacts referenced by Motif.maxpat.
  rm('max/library.html', { force: true }),
  rm('max/motif-device.js', { force: true }),
  rm('max/motif-preview.js', { force: true }),
]);

await writeFile('dist/motif-device.js', output);
await writeFile(path.join('max', engineFilename), output);
await writeFile(path.join('max', previewFilename), preview);
await generateMaxPatch({ engineFilename, previewFilename });
await rm('dist/motif-device.js.map', { force: true });
await rm('max/motif-device.js.map', { force: true });
