import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Motif } from '../src/core/types.js';

export async function generateBuiltins(): Promise<void> {
  const directory = path.resolve('motifs/builtin');
  const files = (await readdir(directory)).filter((file) => file.endsWith('.json')).sort();
  const motifs: Motif[] = [];
  for (const file of files) {
    motifs.push(JSON.parse(await readFile(path.join(directory, file), 'utf8')) as Motif);
  }

  const output = `// Generated by scripts/generate-builtins.ts.
import type { Motif } from '../core/types.js';

export const BUILTIN_MOTIFS = ${JSON.stringify(motifs, null, 2)} as const satisfies readonly Motif[];
`;
  await writeFile('src/generated/builtins.ts', output);
}

const isMain = process.argv[1] !== undefined
  && path.resolve(fileURLToPath(import.meta.url)) === path.resolve(process.argv[1]);

if (isMain) {
  await generateBuiltins();
}
